
services:
  jimdur-app:
    image: jimdur-app:latest
    container_name: jimdur-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - jimdur-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: jimdur-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_jimdur
      MYSQL_USER: jimdur_user
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - jimdur-network
    volumes:
      - mysql-volumen:/var/lib/mysql
networks:
  jimdur-network:
volumes:
  mysql-volumen: